name: _ktop-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - conda-build <3
  - constructor
  - giflib
  - jupyterlab_launcher
  - libpng
  - matplotlib
  - nodejs
  - notebook
  - pandas
  - python >=3.6,<3.7
  - setuptools
