name: notebook-widget

channels:
  - conda-forge
  - defaults

dependencies:
  - nodejs
  - notebook
  - pandas
  - python >=3.6,<3.7
  - setuptools
  - matplotlib
  - jupyterlab_launcher
  - giflib
  - libpng
