{% set name = "KTOP" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [py2k]

requirements:
  build:
    - python
    - setuptools
  run:
    - ipywidgets
    - jupyterlab
    - notebook
    - python

test:
  imports:
    - ktop

about:
  home: https://ripxl.github.io/ktop
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Treat Multiple Notebooks and Kernels like code

  description: |
    `ktop` gives you reactive Notebooks and Kernels:
    - create, open, and save notebooks on-the-fly in memory, or on disk
    - modify and execute cells in one or more kernels
    - react to conditions in running kernels
    - view and link to remote Widgets
  doc_url: http://ripxl.github.io/ktop
  dev_url: https://github.com/ripxl/ktop

extra:
  recipe-maintainers:
    - bollwyvl
    - tonyfast
